<a href="https://colab.research.google.com/github/Mileye22/Mileye22/blob/main/IrisDs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MUSA IDRIS OLALEYE
## POISE DATA SCIENCE (STREAM 4)


In [249]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

%matplotlib inline

""" imported necessary libraries to scan through the data sets """

' imported necessary libraries to scan through the data sets '

In [250]:
dataset = sns.load_dataset('iris')

""" loaded the dataset with seaborn since iris dataset is present in it """

' loaded the dataset with seaborn since iris dataset is present in it '

In [251]:
dataset


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [252]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

There is no need for rescaling of dataset since the data range of the datasets are close.

In [253]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Before Classifing we need to convert our categorical data sets to numeric values i.e setosa = 0, vericolor = 1 ,virginica = 2

In [254]:
dataset.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [255]:
species_co = { 'setosa': 0, 'versicolor': 1, 'virginica' : 2 }

'''Creates a dictionary that maps the species to numerical values'''

'Creates a dictionary that maps the species to numerical values'

In [256]:
species_co

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

In [257]:
dataset['species_co'] = dataset.species.map(species_co)

'''Add new columns into dataset by using the .map() methods'''

'Add new columns into dataset by using the .map() methods'

In [258]:
dataset

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     species_co  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
145           2  
146           2  
147           2  
148           2  
149           2  

[150 rows x 6 columns]

In [259]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

'''imported necessary libraries for classification'''


'imported necessary libraries for classification'

In [260]:
x = dataset.iloc[:, :-2].values
y = dataset.iloc[:, -1].values


'''defining our dependent and independent variables'''

'defining our dependent and independent variables'

In [261]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [262]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [263]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=.33, random_state = 0)

'''Splitting data sets into train and test data'''

'Splitting data sets into train and test data'

In [264]:
classifier = KNeighborsClassifier(n_neighbors= 5, metric = 'minkowski', p = 1)

'''Using Knn as our classifier with k = 5 and metric = manhattan since p= 1 for minkowski denotes the manhattan distance'''

'Using Knn as our classifier with k = 5 and metric = manhattan since p= 1 for minkowski denotes the manhattan distance'

In [265]:
classifier.fit(X_train, Y_train)

KNeighborsClassifier(p=1)

In [266]:
y_pred = classifier.predict(X_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2])

In [267]:
Y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2])

In [268]:
cm = confusion_matrix(Y_test,y_pred)
cm


array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  0, 15]])

In [269]:
np.diag(cm).sum()

49

In [270]:
cm.sum()

50

In [271]:
''' Evaluates the accuracy of the model'''

Accuracy = (np.diag(cm).sum()/cm.sum())* 100
print(f'Accuracy : {Accuracy} %')


Accuracy : 98.0 %
